<?php
	// 生成随机的ID用于多个editor
	$token = \M\Common\Token\Token::getRandChar(32);
  var_dump($token);
?>
<form action="<?=$url?>" method="POST" id="<?='form_'.$token?>">
  <div id="<?='editor_'.$token?>"><?=$content?></div>
  <div class="form-group">
    <div class="col-sm-10">
      <button type="button" id="<?='btn_'.$token?>" class="btn btn-default">提交</button>
    </div>
  </div>
</form>
<script>
	$(function(){
		// 商品详情的富文本编辑器
    var E = window.wangEditor
    var editor = new E('#'+"<?='editor_'.$token?>")
    // 配置菜单
    editor.customConfig.menus = [
      'head',  // 标题
      'bold',  // 粗体
      'italic',  // 斜体
      'underline',  // 下划线
      'strikeThrough',  // 删除线
      'foreColor',  // 文字颜色
      'backColor',  // 背景颜色
      'link',  // 插入链接
      'list',  // 列表
      'justify',  // 对齐方式
      'image',  // 插入图片
      'table',  // 表格
      'undo',  // 撤销
    ]
    // 上传图片路径
    editor.customConfig.uploadImgServer = '/product/file'
    // 隐藏“网络图片”tab
    editor.customConfig.showLinkImg = false
    // 将图片大小限制为 3M
    editor.customConfig.uploadImgMaxSize = 3 * 1024 * 1024
    // 限制一次最多上传 1 张图片
    editor.customConfig.uploadImgMaxLength = 1
    // 设置z-index
    editor.customConfig.zIndex = 10
    editor.customConfig.uploadImgHooks = {
      customInsert: function (insertImg, result, editor) {
      // 图片上传并返回结果，自定义插入图片的事件（而不是编辑器自动插入图片！！！）
      // insertImg 是插入图片的函数，editor 是编辑器对象，result 是服务器端返回的结果

      // 举例：假如上传图片成功后，服务器端返回的是 {url:'....'} 这种格式，即可这样插入图片：
      // var url = result.url
      // insertImg(url)
      // result 必须是一个 JSON 格式字符串！！！否则报错
        switch (result.code) {
            case 0:
                var url = result.url
                insertImg(url)
            break;
            case 11:
                alert(result.error);
            break;
        }
      }
    }

    editor.create()

    $('#'+"<?='btn_'.$token?>").click(function(){
      // 创建表单数据
      var input = "<textarea class='hide' name='content'>"+editor.txt.html()+"</textarea>";
      $('#'+"<?='form_'.$token?>").append(input);
      $('#'+"<?='form_'.$token?>").submit();
    })
	})
</script>