<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>找不到该页面</title>
  <link href="/adminex/css/style.css" rel="stylesheet">
</head>

<body class="error-page">
<section>
  <div class="container ">
    <section class="error-wrapper text-center">
      <h1><img alt="" src="/adminex/images/404-error.png"></h1>
      <h2>403</h2>
      <h3>没有权限</h3>
      <a class="back-btn" href="<?=URL('login')?>"><?=H('返回主页')?></a>
    </section>
  </div>
</section>
</body>
</html>
