<div class="page-heading">
  <h3>
    <?=H('模块')?>
  </h3>
  <ul class="breadcrumb">
    <li>
      <a href="<?=URL('admin/layout')?>">
        <?=H('Gowild')?>
      </a>
    </li>
    <li>
      <a href="<?=URL('admin/layout')?>">
        <?=H('微信')?>
      </a>
    </li>
    <li class="active">
      <?=H('模块管理')?>
    </li>
  </ul>
</div>
<div class="row">
  <div class="col-sm-8">
    <section class="panel">
      <header class="panel-heading">
        <?=H('模块列表')?>
      </header>

      <!-- 列表主体 -->
      <div class="panel-body">
        <div class="adv-table editable-table ">
          <div class="clearfix">

            <!-- 添加product -->
            <div class="btn-group">
              <a href="#myModal" data-toggle="modal" class="btn btn-primary">
                <?=H('添加模块')?>
              </a>
            </div>

            <!-- 列表打印 -->
            <div class="btn-group pull-right">
              <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                <?=H('打印')?>
              </button>
              <ul class="dropdown-menu pull-right">
                <li><a href="#"><?=H('Web打印')?></a></li>
                <li><a href="#"><?=H('Pdf打印')?></a></li>
                <li><a href="#"><?=H('Excel打印')?></a></li>
              </ul>
            </div>
          </div>

          <div class="space15"></div>

          <!-- 表数据主体 -->
          <table class="table table-striped table-hover table-bordered" id="editable-sample">
            <!-- 表头 -->
            <thead>
              <tr>
                <th><?=H('ID')?></th>
                <th><?=H('名称')?></th>
                <th><?=H('创建时间')?></th>
                <th><?=H('状态')?></th>
                <th><?=H('修改')?></th>
              </tr>
            </thead>

            <tbody>
              <?php foreach ($categorys as $category) :?>
              <tr class="">
                <td><?=H('#'.$category->id)?></td>
                <td><?=H($category->name)?></td>
                <td><?=H($category->ctime)?></td>
                <td>
                  <span class="label label-mini <?=\M\ORM\Category::$class[$category->status]?>">
                    <?=H(\M\ORM\Category::$statuses[$category->status])?>
                  </span>
                </td>
                <td><a href="<?=URL('category/info/'.$category->id)?>">修改</a></td>
              </tr>
              <?php endforeach;?>
            </tbody>
          </table>
        </div>
      </div>
    </section>
  </div>
</div>
<!-- Modal -->
<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <form action="<?=URL('category/add')?>" method="POST" id="add-category-form">
        <div class="modal-header">
          <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
          <h4 class="modal-title"><?=H('添加')?></h4>
        </div>
        <div class="modal-body">
          <section class="panel">
            <div class="panel-body">
              <div class="form-group">
                  <label for="exampleInputEmail1"><?=H('名称')?></label>
                  <input type="text" class="form-control" name="name">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1"><?=H('状态')?></label>
                <select class="form-control m-bot15" name="status">
                  <option value="0">启用</option>
                  <option value="1">禁用</option>
                </select>
            </div>
          </section>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal"><?=H('关闭')?></button>
            <button type="submit" class="btn btn-success"><?=H('保存')?></button>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- modal -->
<script>
    jQuery(document).ready(function() {
        EditableTable.init();
    });
</script>