<div class="page-heading">
  <h3>
    <?=H('商品')?>
  </h3>
  <ul class="breadcrumb">
    <li>
      <a href="<?=URL('admin/layout')?>">
        <?=H('Gowild')?>
      </a>
    </li>
    <li>
      <a href="<?=URL('admin/layout')?>">
        <?=H('微信')?>
      </a>
    </li>
    <li class="active">
      <?=H('商品列表')?>
    </li>
  </ul>
</div>
<div class="row">
  <div class="col-sm-8">
    <section class="panel">
      <header class="panel-heading">
        <?=H('商品列表')?>
      </header>

      <!-- 列表主体 -->
      <div class="panel-body">
        <div class="adv-table editable-table ">
          <div class="clearfix">

            <!-- 添加product -->
            <div class="btn-group">
              <a href="#myModal" data-toggle="modal" class="btn btn-primary">
                添加商品
              </a>
            </div>

            <!-- 列表打印 -->
            <div class="btn-group pull-right">
                <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                  <?=H('打印')?>
                </button>
                <ul class="dropdown-menu pull-right">
                    <li><a href="#"><?=H('Web打印')?></a></li>
                    <li><a href="#"><?=H('Pdf打印')?></a></li>
                    <li><a href="#"><?=H('Excel打印')?></a></li>
                </ul>
            </div>
          </div>

          <div class="space15"></div>

          <!-- 表数据主体 -->
          <table class="table table-striped table-hover table-bordered" id="editable-sample">
            <!-- 表头 -->
            <thead>
              <tr>
                <th><?=H('ID')?></th>
                <th><?=H('名称')?></th>
                <th><?=H('价格')?></th>
                <th><?=H('库存')?></th>
                <th><?=H('操作')?></th>
              </tr>
            </thead>

            <tbody>
              <?php foreach ($products as $product) :?>
              <tr class="">
                <td><?=H('#'.$product->id)?></td>
                <td><?=H($product->name)?></td>
                <td><?=H($product->price)?></td>
                <td><?=H($product->stock)?></td>
                <td><a href="<?=URL('product/info/'.$product->id)?>">修改</a></td>
              </tr>
              <?php endforeach;?>
            </tbody>
          </table>
        </div>
      </div>
    </section>
  </div>
</div>
<!-- Modal -->
<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
          <form action="<?=URL('product/add')?>" method="POST" >
            <div class="modal-header">
                <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                <h4 class="modal-title"><?=H('添加商品基础信息')?></h4>
            </div>
            <div class="modal-body">
              <section class="panel">
                <div class="panel-body">
                  <div class="form-group">
                    <label for="exampleInputEmail1"><?=H('名称')?></label>
                    <input type="text" class="form-control" name="name">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1"><?=H('价格')?></label>
                    <input type="text" class="form-control" name="price">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1"><?=H('库存')?></label>
                    <input type="text" class="form-control" name="stock">
                  </div>
                </div>
              </section>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal"><?=H('关闭')?></button>
              <button type="submit" class="btn btn-success"><?=H('保存')?></button>
            </div>
          </form>
        </div>
    </div>
</div>
<!-- modal -->
<script>
jQuery(document).ready(function() {
  EditableTable.init();
});
</script>